### ISSUE TITLE
Minimal Promise.prototype methods?

### ISSUE THREAD

**Issue by michaelfig** [Agoric/proposal-infix-bang#1]
Is it worthwhile to add `fapply`, `fcall`, and `invoke` to the proposal?  I've left them out for now, but if there's a convincing argument to allow them, please let me know.

They're sugar for sugar, and their absence of `this` and different naming makes them unnecessary and potentially confusing.  I'd rather be minimal.

Thoughts?

**Comment by michaelfig** [comment]
I've added them for now, please reopen if you would like them removed.

**Comment by erights** [comment]
What changed your mind?

**Comment by michaelfig** [comment]
I didn't want to be lazy.
